name: sngine_messenger
description: Sngine Messnger

version: 2.1.0+7

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # core
  cupertino_icons: ^1.0.9
  http: ^1.6.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  url_launcher: ^6.3.2
  flutter_svg: ^2.3.0
  video_player: ^2.11.1
  path_provider: ^2.1.5
  crypto: ^3.0.7

  # routing
  auto_route: ^11.1.0

  # state management
  flutter_riverpod: ^3.3.1

  # localization
  easy_localization: ^3.0.8

  # push notifications
  onesignal_flutter: ^5.5.4

  # socket.io
  socket_io_client: 1.0.2

  # utils
  uuid: ^4.5.3
  permission_handler: ^12.0.1
  device_info_plus: any
  share_plus: ^13.1.0
  timeago_flutter: ^3.7.0
  logger: ^2.7.0

  # images
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_image_gallery_saver: ^2.0.0

  # videos
  chewie: ^1.14.0
  video_thumbnail: ^0.5.6

  # voice messages
  record: ^6.2.0
  voice_message_package: ^2.2.1

  # audio
  audioplayers: ^6.6.0

  # UI
  flutter_slidable: ^4.0.3
  flutter_spinkit: ^5.2.2
  flutter_html: ^3.0.0
  multi_select_flutter: ^4.1.3
  pinput: ^6.0.2
  qr_flutter: ^4.1.0
  html_unescape: ^2.0.0

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  riverpod_lint: ^3.1.3
  build_runner: ^2.15.0

dev_dependency_overrides:
  custom_lint: ^0.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/chat/
    - assets/images/icons/navbar/
    - assets/images/icons/settings/
    - assets/images/icons/social/
    - assets/translations/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
